splint: audit fix
fix audit from error message:

```
splint:
 * Use `assert_match` instead of `assert ...include?`

Error: 1 problem in 1 formula
```

Closes Homebrew/homebrew#46786.

Signed-off-by: Mike McQuaid <mike@mikemcquaid.com>