libdrm: rebuild
* BUGIFX: Added cairo as dependency
  Building libdrm failed because of missing cairo.h:

  ```
  tests/util/libutil.a.p/pattern.c.o.d -o tests/util/libutil.a.p/pattern.c.o -c ../tests/util/pattern.c
  ../tests/util/pattern.c:34:10: fatal error: cairo.h: No such file or directory
  34 | #include <cairo.h>
  |          ^~~~~~~~~
  compilation terminated.
  ```
* BUGFIX: Fixed dependency order
* BUGFIX: Changed dependency order (again)
* TASK: Removed trailing whitespaces
* libdrm: disable cairo usage

Closes #100868.

Co-authored-by: Sean Molenaar <SMillerDev@users.noreply.github.com>
Signed-off-by: Sean Molenaar <1484494+SMillerDev@users.noreply.github.com>
Signed-off-by: BrewTestBot <1589480+BrewTestBot@users.noreply.github.com>