graphicsmagick: disable jpeg-xl support
Requires an unreleased version of libjxl:

```
coders/jxl.c:811:3: error: use of undeclared identifier 'JxlEncoderFrameSettings'
  JxlEncoderFrameSettings
  ^
```