libxcb: the requirement does not need a build env
Fixes (on linux):
RuntimeError: The requested Homebrew GCC was not installed. You must:
brew install gcc