verapdf 1.23.144
* verapdf 1.23.144
* verapdf: use openjdk@17
  ```
  Caused by: java.io.IOException: Error while instrumenting java/sql/Time.
  ...
  Caused by: java.lang.IllegalArgumentException: Unsupported class file major version 63
  ...
  java.lang.instrument.IllegalClassFormatException: Error while instrumenting java/sql/Timestamp.
  ```
* verapdf: use JDK 17 for maven

Closes #121273.

Co-authored-by: Rui Chen <rui@chenrui.dev>
Co-authored-by: Sean Molenaar <SMillerDev@users.noreply.github.com>
Signed-off-by: Rui Chen <rui@chenrui.dev>
Signed-off-by: BrewTestBot <1589480+BrewTestBot@users.noreply.github.com>