ghostscript 9.07
This update no longer builds against hombrew lcms2, because the modified
version that ships with ghostscript is incompatible. Without this change
the build would fail with this error:

  "_cmsPluginTHR", referenced from:
    _gscms_create in gsicc_lcms2.o
    ld: symbol(s) not found for architecture x86_64

Closes Homebrew/homebrew#18686.

Signed-off-by: Adam Vandenberg <flangy@gmail.com>