infer: depend on patchelf on Linux (#78436)
Fixes:
echo "ERROR: ldd (Linux?) found but not patchelf, please install patchelf" >&2; exit 1
ERROR: ldd (Linux?) found but not patchelf, please install patchelf
Makefile:673: recipe for target 'install-with-libs' failed
make: *** [install-with-libs] Error 1