pandoc-citeproc 0.10.2.1
Constraining aeson to < 1.0.0.0 avoids

```
src/Text/CSL/Reference.hs:386:8: error:
    • Overlapping instances for FromJSON [Agent]
        arising from a use of ‘.:?’
      Matching instances:
        instance FromJSON a => FromJSON [a]
          -- Defined in ‘aeson-1.0.2.1:Data.Aeson.Types.FromJSON’
        instance FromJSON [Agent]
          -- Defined at src/Text/CSL/Style.hs:907:10
    • In the first argument of ‘(.!=)’, namely ‘v .:? "author"’
      In the second argument of ‘(<*>)’, namely ‘v .:? "author" .!= []’
      In the first argument of ‘(<*>)’, namely
        ‘Reference <$> v .:? "id" .!= "" <*> v .:? "type" .!= NoType
         <*> v .:? "author" .!= []’
```

Solver ends up choosing aeson-0.11.2.1, the same as lts-7.4, which is
what upstream specifies in stack.yaml

Closes #6322.

Signed-off-by: ilovezfs <ilovezfs@icloud.com>