cayley: fix audit error
This PR fixed error called `brew audit cayley`, It show message below.

```
$ brew audit cayley
cayley:
 * Use `assert_match` instead of `assert ...include?`

Error: 1 problem in 1 formula
```

Closes Homebrew/homebrew#46734.

Signed-off-by: Mike McQuaid <mike@mikemcquaid.com>