c-kermit: fix test, fix code style issues (#3034)
Testing with the `PWD` command turns out to be problematic because it
prints the real path, but `testpath` is the logical path, resulting in:

  ==> /usr/local/Cellar/c-kermit/9.0.302/bin/kermit -C PWD,exit
  Error: c-kermit: failed
  <"/tmp/c-kermit-test-20160711-81517-1v46fdo"> expected but was
  <"/private/tmp/c-kermit-test-20160711-81517-1v46fdo">.