czmq: rename executable
The curse of generic naming strikes again.

```
Error: The `brew link` step did not complete successfully
The formula built, but is not symlinked into /usr/local
Could not symlink bin/makecert
Target /usr/local/bin/makecert
is a symlink belonging to czmq. You can unlink it:
  brew unlink czmq

To force the link and overwrite all conflicting files:
  brew link --overwrite mono

To list all files that would be deleted:
  brew link --overwrite --dry-run mono

Possible conflicting files are:
/usr/local/bin/makecert -> /usr/local/Cellar/czmq/3.0.2/bin/makecert
```

Since czmq tends to be used as a library more than for cert generation, let's rename
this one.

Closes Homebrew/homebrew#41353.

Signed-off-by: Dominyk Tiller <dominyktiller@gmail.com>