c-kermit: rebuild
* c-kermit: depend on libxcrypt
  Fixes:

  Full linkage --test c-kermit output
  Unwanted system libraries:
  /lib/x86_64-linux-gnu/libcrypt.so.1
  Error: Calling linkage to libcrypt.so.1 is disabled! Use libcrypt.so.2 in the libxcrypt formula instead.
* c-kermit: fix build with newer glibc

Closes #119598.

Co-authored-by: danielnachun <daniel.nachun@gmail.com>
Signed-off-by: Daniel Nachun <9205048+danielnachun@users.noreply.github.com>
Signed-off-by: BrewTestBot <1589480+BrewTestBot@users.noreply.github.com>