gegl: depend on poppler on Linux
Fixes:
  ../operations/external/pdf-load.c:53:10: fatal error: poppler.h: No such file or directory
     53 | #include <poppler.h>
        |          ^~~~~~~~~~~
  compilation terminated.